<?php

declare(strict_types=1);

namespace HeadlessChrome\Tests;

use HeadlessChrome\Chrome;
use PHPUnit\Framework\TestCase;

class ChromeTest extends TestCase
{
    static $chrome;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        self::$chrome = new Chrome('/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome');
    }

    public function testToLaunchChrome(): void
    {
        $this->assertTrue(self::$chrome->isRunning());
        $this->assertStringContainsString('ws://localhost', self::$chrome->getEndpoints()[0]->webSocketDebuggerUrl);
    }

    public function testToMovePage(): void
    {
        $page = self::$chrome->getPage(0);
        $page->moveTo('https://twitter.com/login');
        $this->assertEquals($page->title, 'Twitterにログイン');
        $this->assertEquals($page->url,'https://twitter.com/login');
    }

    public function testToCapture(): void
    {
        $page = self::$chrome->getPage(0);
        $page->moveTo('https://twitter.com/login');
        $page->captureTo('./capture.png');
        $this->assertFileExists('./capture.png');
        unlink('./capture.png');
    }
}
